"""Parser for GRN.xls (Goods Receipt Note).

The srimukha GRN export has 95 columns, of which we load the subset that
maps to the `grn` table. Duplicate header names (the file has three columns
literally named `Type`) are handled by build_header_map — first match wins.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List

from ._common import (
    PathOrBytes,
    build_header_map,
    coerce_date,
    coerce_decimal,
    coerce_int,
    coerce_str,
    iter_data_rows,
    load_workbook_flex,
    select_sheet,
)

log = logging.getLogger(__name__)

ALIASES = {
    "unit":             ["Unit"],
    "unit_desc":        ["Unit Desc", "Unit Desc.", "Unit Description"],
    "ref_unit":         ["Ref. Unit", "Ref Unit"],
    "territory":        ["Territory"],
    "ref_unit_desc":    ["Ref. Unit Desc", "Ref Unit Desc."],
    "dc_no":            ["DC No", "DC No."],
    "dc_date":          ["DC Date"],
    "gate_entry_no":    ["Gate Entry No", "Gate Entry No."],
    "gunny_bags":       ["Gunny Bags"],
    "hdpe_bags":        ["HDPE Bags"],
    "gross_weight":     ["Gross Weight"],
    "tare_weight":      ["Tare Weight"],
    "nett_weight":      ["Nett Weight"],
    "supplier_doc_no":  ["Supplier Doc. No", "Supplier Doc No", "Supplier Doc. No."],
    "supplier_doc_date": ["Supplier Doc. Date", "Supplier Doc Date", "Supplier Doc. Date."],
    "grn_pfx":          ["GRN Pfx", "GRN Pfx."],
    "grn_no":           ["GRN No", "GRN No."],
    "grn_line":         ["GRN Line"],
    "grn_date":         ["GRN Date"],
    "grn_year":         ["GRN Year"],
    "grn_period":       ["GRN Period"],
    "exchange_rate":    ["Exchange Rate"],
    "supplier":         ["Supplier"],
    "supplier_name":    ["Supplier Name"],
    "type":             ["Type"],  # first occurrence wins
    "pr_type":          ["PR Type"],
    "item":             ["Item"],
    "rev":              ["Rev", "Rev."],
    "description_1":    ["Description 1"],
    "uom":              ["UOM"],
    "unit_cost":        ["UNIT COST", "Unit Cost"],
    "grn_qty":          ["GRN Qty", "GRN Qty."],
    "disc_amt":         ["Disc. Amt.", "Disc Amt", "Disc. Amt"],
    "tax_amount":       ["Tax Amount", "Tax Amt", "Tax Amt."],
    "receipt_qty_toler": ["Receipt Qty. (Toler.)", "Receipt Qty Toler"],
    "accepted_qty":     ["Accepted Qty", "Accepted Qty."],
    "rejected_qty":     ["Rejected Qty", "Rejected Qty."],
    "return_qty":       ["Return Qty", "Return Qty."],
    "rework_qty":       ["Rework Qty", "Rework Qty."],
    "excess_qty":       ["Excess Qty", "Excess Qty."],
    "excess_rtn_qty":   ["Excess Rtn. Qty", "Excess Rtn Qty", "Excess Rtn. Qty."],
    "invoice_qty":      ["Invoice Qty", "Invoice Qty."],
    "tax":              ["Tax"],
    "tax_desc":         ["Tax Desc", "Tax Desc."],
    "warehouse":        ["Warehouse"],
    "warehouse_desc":   ["Warehouse Desc", "Warehouse Desc."],
    "qc_pfx":           ["QC Pfx", "QC Pfx."],
    "qc_no":            ["QC No", "QC No."],
    "required_qty":     ["Required Qty", "Required Qty."],
    "required_date":    ["Required Date"],
    "promise_date":     ["Promise Date"],
    "buyer":            ["Buyer"],
    "buyer_name":       ["Buyer Name"],
    "process_group":    ["Process/Group", "Process Group"],
    "process_desc":     ["Process Desc", "Process Desc."],
    "class":            ["Class"],
    "class_desc":       ["Class Desc", "Class Desc."],
    "sub_class":        ["Sub Class"],
    "sub_class_desc":   ["Sub Class Desc", "Sub Class Desc."],
    "group_desc":       ["Group Desc", "Group Desc."],
    "sub_group_desc":   ["Sub Group Desc", "Sub Group Desc."],
    "po_pfx":           ["PO Pfx", "PO Pfx."],
    "po_no":            ["PO No", "PO No."],
    "po_line":          ["PO Line"],
    "po_schld":         ["PO Schld", "PO Schld."],
    "ss_pfx":           ["SS Pfx", "SS Pfx."],
    "ss_no":            ["SS No", "SS No."],
    "ss_line":          ["SS Line"],
    "open_order_pfx":   ["Open Order Pfx", "Open Order Pfx."],
    "open_order_no":    ["Open Order No", "Open Order No."],
    "amd_no":           ["Amd. No", "Amd No", "Amd. No."],
    "assessable_value": ["Assessable Value"],
    "commodity_code":   ["Commodity Code"],
    "bom_no":           ["BOM No", "BOM No."],
    "prod_ord_no":      ["Prod. Ord. No", "Prod Ord No", "Prod. Ord. No."],
    "sf_code":          ["SF Code"],
    "completed_process": ["Completed Process"],
    "test_cert_req":    ["Test Cert. Req.", "Test Cert Req"],
    "cert_ins":         ["Cert. Ins.", "Cert Ins"],
    "description":      ["Description"],
    "bom":              ["BOM"],
    "reference":        ["Reference"],  # first occurrence wins (file has duplicate)
    "work_order_no":    ["Work Order No", "Work Order No."],
    "task":             ["Task"],
    "thickness":        ["Thickness"],
    "length":           ["Length"],
    "width":            ["Width"],
    "qty_nos":          ["Qty. Nos.", "Qty Nos"],
    "header_status":    ["Header Status"],
    "line_status":      ["Line Status"],
    "gst_type":         ["GST Type"],
    "gstin_no":         ["GSTIN No", "GSTIN No."],
}

REQUIRED = ("grn_no",)


def parse(source: PathOrBytes) -> List[Dict[str, Any]]:
    wb = load_workbook_flex(source)
    try:
        ws = select_sheet(wb)
        header_row, col_map = build_header_map(ws, ALIASES, required=REQUIRED)
        log.debug("grn parser: header_row=%d columns=%d", header_row, len(col_map))
        rows: List[Dict[str, Any]] = []
        for raw in iter_data_rows(ws, header_row, col_map):
            grn_no = coerce_str(raw.get("grn_no"), max_len=50)
            if not grn_no:
                continue
            rows.append(
                {
                    "unit":              coerce_str(raw.get("unit"), max_len=50),
                    "unit_desc":         coerce_str(raw.get("unit_desc"), max_len=255),
                    "ref_unit":          coerce_str(raw.get("ref_unit"), max_len=50),
                    "territory":         coerce_str(raw.get("territory"), max_len=50),
                    "ref_unit_desc":     coerce_str(raw.get("ref_unit_desc"), max_len=255),
                    "dc_no":             coerce_str(raw.get("dc_no"), max_len=50),
                    "dc_date":           coerce_date(raw.get("dc_date")),
                    "gate_entry_no":     coerce_str(raw.get("gate_entry_no"), max_len=50),
                    "gunny_bags":        coerce_int(raw.get("gunny_bags")),
                    "hdpe_bags":         coerce_int(raw.get("hdpe_bags")),
                    "gross_weight":      coerce_decimal(raw.get("gross_weight")),
                    "tare_weight":       coerce_decimal(raw.get("tare_weight")),
                    "nett_weight":       coerce_decimal(raw.get("nett_weight")),
                    "supplier_doc_no":   coerce_str(raw.get("supplier_doc_no"), max_len=50),
                    "supplier_doc_date": coerce_date(raw.get("supplier_doc_date")),
                    "grn_pfx":           coerce_str(raw.get("grn_pfx"), max_len=50),
                    "grn_no":            grn_no,
                    "grn_line":          coerce_int(raw.get("grn_line")),
                    "grn_date":          coerce_date(raw.get("grn_date")),
                    "grn_year":          coerce_int(raw.get("grn_year")),
                    "grn_period":        coerce_int(raw.get("grn_period")),
                    "exchange_rate":     coerce_decimal(raw.get("exchange_rate")),
                    "supplier":          coerce_str(raw.get("supplier"), max_len=50),
                    "supplier_name":     coerce_str(raw.get("supplier_name"), max_len=255),
                    "type":              coerce_str(raw.get("type"), max_len=50),
                    "pr_type":           coerce_str(raw.get("pr_type"), max_len=50),
                    "type_1":            None,  # dup columns collapse to a single alias
                    "item":              coerce_str(raw.get("item"), max_len=50),
                    "rev":               coerce_int(raw.get("rev")),
                    "description_1":     coerce_str(raw.get("description_1")),
                    "uom":               coerce_str(raw.get("uom"), max_len=50),
                    "unit_cost":         coerce_decimal(raw.get("unit_cost")),
                    "grn_qty":           coerce_decimal(raw.get("grn_qty")),
                    "disc_amt":          coerce_decimal(raw.get("disc_amt")),
                    "tax_amount":        coerce_decimal(raw.get("tax_amount")),
                    "receipt_qty_toler": coerce_decimal(raw.get("receipt_qty_toler")),
                    "accepted_qty":      coerce_decimal(raw.get("accepted_qty")),
                    "rejected_qty":      coerce_decimal(raw.get("rejected_qty")),
                    "return_qty":        coerce_decimal(raw.get("return_qty")),
                    "rework_qty":        coerce_decimal(raw.get("rework_qty")),
                    "excess_qty":        coerce_decimal(raw.get("excess_qty")),
                    "excess_rtn_qty":    coerce_decimal(raw.get("excess_rtn_qty")),
                    "invoice_qty":       coerce_decimal(raw.get("invoice_qty")),
                    "tax":               coerce_str(raw.get("tax"), max_len=50),
                    "tax_desc":          coerce_str(raw.get("tax_desc"), max_len=255),
                    "warehouse":         coerce_str(raw.get("warehouse"), max_len=50),
                    "warehouse_desc":    coerce_str(raw.get("warehouse_desc"), max_len=255),
                    "qc_pfx":            coerce_str(raw.get("qc_pfx"), max_len=50),
                    "qc_no":             coerce_str(raw.get("qc_no"), max_len=50),
                    "required_qty":      coerce_decimal(raw.get("required_qty")),
                    "required_date":     coerce_date(raw.get("required_date")),
                    "promise_date":      coerce_date(raw.get("promise_date")),
                    "buyer":             coerce_str(raw.get("buyer"), max_len=50),
                    "buyer_name":        coerce_str(raw.get("buyer_name"), max_len=255),
                    "type_2":            None,
                    "process_group":     coerce_str(raw.get("process_group"), max_len=50),
                    "process_desc":      coerce_str(raw.get("process_desc")),
                    "class":             coerce_str(raw.get("class"), max_len=50),
                    "class_desc":        coerce_str(raw.get("class_desc"), max_len=255),
                    "sub_class":         coerce_str(raw.get("sub_class"), max_len=50),
                    "sub_class_desc":    coerce_str(raw.get("sub_class_desc"), max_len=255),
                    "group_desc":        coerce_str(raw.get("group_desc"), max_len=255),
                    "sub_group_desc":    coerce_str(raw.get("sub_group_desc"), max_len=255),
                    "po_pfx":            coerce_str(raw.get("po_pfx"), max_len=50),
                    "po_no":             coerce_str(raw.get("po_no"), max_len=50),
                    "po_line":           coerce_int(raw.get("po_line")),
                    "po_schld":          coerce_str(raw.get("po_schld"), max_len=50),
                    "ss_pfx":            coerce_str(raw.get("ss_pfx"), max_len=50),
                    "ss_no":             coerce_str(raw.get("ss_no"), max_len=50),
                    "ss_line":           coerce_int(raw.get("ss_line")),
                    "open_order_pfx":    coerce_str(raw.get("open_order_pfx"), max_len=50),
                    "open_order_no":     coerce_str(raw.get("open_order_no"), max_len=50),
                    "amd_no":            coerce_int(raw.get("amd_no")),
                    "assessable_value":  coerce_decimal(raw.get("assessable_value")),
                    "commodity_code":    coerce_str(raw.get("commodity_code"), max_len=50),
                    "bom_no":            coerce_str(raw.get("bom_no"), max_len=50),
                    "prod_ord_no":       coerce_str(raw.get("prod_ord_no"), max_len=50),
                    "sf_code":           coerce_str(raw.get("sf_code"), max_len=50),
                    "completed_process": coerce_str(raw.get("completed_process"), max_len=255),
                    "test_cert_req":     coerce_str(raw.get("test_cert_req"), max_len=50),
                    "cert_ins":          coerce_str(raw.get("cert_ins"), max_len=50),
                    "description":       coerce_str(raw.get("description")),
                    "bom":               coerce_str(raw.get("bom"), max_len=50),
                    "reference":         coerce_str(raw.get("reference"), max_len=255),
                    "work_order_no":     coerce_str(raw.get("work_order_no"), max_len=50),
                    "task":              coerce_str(raw.get("task"), max_len=50),
                    "thickness":         coerce_decimal(raw.get("thickness")),
                    "length":            coerce_decimal(raw.get("length")),
                    "width":             coerce_decimal(raw.get("width")),
                    "qty_nos":           coerce_decimal(raw.get("qty_nos")),
                    "reference_1":       None,
                    "header_status":     coerce_str(raw.get("header_status"), max_len=50),
                    "line_status":       coerce_str(raw.get("line_status"), max_len=50),
                    "gst_type":          coerce_str(raw.get("gst_type"), max_len=50),
                    "gstin_no":          coerce_str(raw.get("gstin_no"), max_len=50),
                }
            )
    finally:
        wb.close()
    return rows
